final List<Map<String, dynamic>> categoriesJson = [
  {'name': 'Frutas', 'imageUrl': 'https://i.postimg.cc/SNX7hc6F/Image.png'},
  {
    'name': 'Verduras',
    'imageUrl': 'https://i.postimg.cc/8PFBSLh2/Image-(1).png',
  },
  {'name': 'Padaria', 'imageUrl': 'https://i.postimg.cc/xTky2LvV/Image-1.png'},
  {
    'name': 'Importados',
    'imageUrl': 'https://i.postimg.cc/Yq4fHQ6w/Image-2.png',
  },
];

final List<Map<String, dynamic>> productsJson = [
  {
    'brand': 'Akatsu',
    'name': 'Acerola',
    'imageUrl': 'https://i.postimg.cc/BQMWr9B8/Image.png',
    'price': 7.99,
    'category': 'Frutas',
  },
  {
    'brand': 'Natural da Terra',
    'name': 'Maçã',
    'imageUrl': 'https://i.postimg.cc/BQMWr9B8/Image.png',
    'price': 8.49,
    'category': 'Frutas',
  },
  {
    'brand': 'Akatsu',
    'name': 'Banana',
    'imageUrl': 'https://i.postimg.cc/BQMWr9B8/Image.png',
    'price': 6.29,
    'category': 'Frutas',
  },
  {
    'brand': 'Natural da Terra',
    'name': 'Morango',
    'imageUrl': 'https://i.postimg.cc/BQMWr9B8/Image.png',
    'price': 9.90,
    'category': 'Frutas',
  },
  {
    'brand': 'Natural da Terra',
    'name': 'Rabanete',
    'imageUrl': 'https://i.postimg.cc/8Pt82Qmf/Image-1.png',
    'price': 10.99,
    'category': 'Verduras',
  },
  {
    'brand': 'Natural da Terra',
    'name': 'Cogumelo',
    'imageUrl': 'https://i.postimg.cc/RVP8P1vw/Image-2.png',
    'price': 12.19,
    'category': 'Verduras',
  },
  {
    'brand': 'Natural da Terra',
    'name': 'Alface',
    'imageUrl': 'https://i.postimg.cc/8Pt82Qmf/Image-1.png',
    'price': 5.49,
    'category': 'Verduras',
  },
  {
    'brand': 'Pão & Cia',
    'name': 'Pão francês',
    'imageUrl': 'https://i.postimg.cc/xTky2LvV/Image-1.png',
    'price': 15.00,
    'category': 'Padaria',
  },
  {
    'brand': 'Pão & Cia',
    'name': 'Baguete',
    'imageUrl': 'https://i.postimg.cc/8Pt82Qmf/Image-1.png',
    'price': 8.75,
    'category': 'Padaria',
  },
  {
    'brand': 'Padaria do Bairro',
    'name': 'Pão de Forma',
    'imageUrl': 'https://i.postimg.cc/xTky2LvV/Image-1.png',
    'price': 12.49,
    'category': 'Padaria',
  },
  {
    'brand': 'Padaria do Bairro',
    'name': 'Croissant',
    'imageUrl': 'https://i.postimg.cc/xTky2LvV/Image-1.png',
    'price': 8.99,
    'category': 'Padaria',
  },
  {
    'brand': 'La Frontera',
    'name': 'Queijo Manchego',
    'imageUrl': 'https://i.postimg.cc/RVP8P1vw/Image-2.png',
    'price': 45.90,
    'category': 'Importados',
  },
  {
    'brand': 'La Frontera',
    'name': 'Chocolate Belga',
    'imageUrl': 'https://i.postimg.cc/BQMWr9B8/Image.png',
    'price': 32.00,
    'category': 'Importados',
  },
  {
    'brand': 'Ferrero',
    'name': 'Nutella',
    'imageUrl': 'https://i.postimg.cc/Yq4fHQ6w/Image-2.png',
    'price': 29.99,
    'category': 'Importados',
  },
  {
    'brand': 'Lindt',
    'name': 'Chocolate Lindt',
    'imageUrl': 'https://i.postimg.cc/Yq4fHQ6w/Image-2.png',
    'price': 24.99,
    'category': 'Importados',
  },
  {
    'brand': 'Pringles',
    'name': 'Batata Pringles',
    'imageUrl': 'https://i.postimg.cc/Yq4fHQ6w/Image-2.png',
    'price': 18.99,
    'category': 'Importados',
  },
];
